export const MODULES = {
  shops: {
    key: "shop",
    title: "Shops",
    blurb: "Commercial shops and units inside Swastik Marvella.",
    add: "Add shop",
    columns: [
      { label: "Shop", key: "title" },
      { label: "Occupant", key: "detail" },
      { label: "Category", key: "category" },
      { label: "Phone", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Shop name / number", required: true },
      { key: "detail", label: "Occupant" },
      { key: "phone", label: "Phone" },
      { key: "category", label: "Category", options: ["grocery", "pharmacy", "cafe", "salon", "bank", "services", "other"] },
      { key: "status", label: "Status", options: ["leased", "owner_operated", "vacant", "overdue", "renewal", "closed"] },
      { key: "notes", label: "Lease / area / notes" },
    ],
  },
  parking: {
    key: "parking",
    title: "Parking",
    blurb: "Parking slots, vehicles, and allotments.",
    add: "Add parking slot",
    columns: [
      { label: "Slot", key: "title" },
      { label: "Vehicle / flat", key: "detail" },
      { label: "Type", key: "status", badge: true },
      { label: "Notes", key: "notes" },
    ],
    fields: [
      { key: "title", label: "Slot number", required: true },
      { key: "detail", label: "Vehicle / flat" },
      { key: "status", label: "Type", options: ["car", "bike", "other"] },
      { key: "notes", label: "Notes" },
    ],
  },
  visitors: {
    key: "visitor",
    title: "Visitors",
    blurb: "Gate entries, guest visits, and in-out records.",
    add: "Add visitor",
    columns: [
      { label: "Visitor", key: "title" },
      { label: "Visiting", key: "detail" },
      { label: "Phone", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Visitor name", required: true },
      { key: "detail", label: "Visiting flat / person" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", options: ["inside", "exited", "expected"] },
      { key: "notes", label: "Purpose" },
    ],
  },
  complaints: {
    key: "complaint",
    title: "Complaints",
    blurb: "Resident issues, tickets, and follow-up.",
    add: "Raise complaint",
    columns: [
      { label: "Complaint", key: "title" },
      { label: "Location", key: "detail" },
      { label: "Category", key: "category" },
      { label: "Assigned", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Subject", required: true },
      { key: "detail", label: "Flat / location" },
      { key: "category", label: "Category", options: ["plumbing", "electrical", "elevator", "intercom", "housekeeping", "carpentry", "other"] },
      { key: "status", label: "Status", options: ["open", "urgent", "in_progress", "resolved"] },
      { key: "phone", label: "Assigned to" },
      { key: "notes", label: "Details" },
    ],
  },
  events: {
    key: "event",
    title: "Events",
    blurb: "Society events, festivals, and gatherings.",
    add: "Add event",
    columns: [
      { label: "Event", key: "title" },
      { label: "When / venue", key: "detail" },
      { label: "Contact", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Event name", required: true },
      { key: "detail", label: "Date and venue" },
      { key: "phone", label: "Contact" },
      { key: "status", label: "Status", options: ["upcoming", "ongoing", "completed"] },
      { key: "notes", label: "Notes" },
    ],
  },
  staff: {
    key: "staff",
    title: "Staff",
    blurb: "Society staff, shifts, and contacts.",
    add: "Add staff",
    columns: [
      { label: "Name", key: "title" },
      { label: "Role", key: "detail" },
      { label: "Phone", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Staff name", required: true },
      { key: "detail", label: "Role / shift" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", options: ["active", "on_leave", "inactive"] },
      { key: "notes", label: "Notes" },
    ],
  },
  security: {
    key: "security",
    title: "Security",
    blurb: "Guard duty, incidents, and gate notes.",
    add: "Add security note",
    columns: [
      { label: "Note", key: "title" },
      { label: "Guard / shift", key: "detail" },
      { label: "Phone", key: "phone" },
      { label: "Status", key: "status", badge: true },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "detail", label: "Guard / shift" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", options: ["logged", "alert", "cleared"] },
      { key: "notes", label: "Details" },
    ],
  },
  documents: {
    key: "document",
    title: "Documents",
    blurb: "Society circulars, policies, and files.",
    add: "Add document",
    columns: [
      { label: "Document", key: "title" },
      { label: "Category", key: "detail" },
      { label: "Status", key: "status", badge: true },
      { label: "Link / notes", key: "notes" },
    ],
    fields: [
      { key: "title", label: "Document name", required: true },
      { key: "detail", label: "Category" },
      { key: "status", label: "Status", options: ["current", "archived"] },
      { key: "notes", label: "Link or notes" },
    ],
  },
};
